name: Test Flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run
        run: python main.py

  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python for Tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Tests
        run: python -m unittest discover