name: Test Flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run
        run: python main.py

  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python for Tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Tests
        run: |
          mkdir -p test_reports
          python -m unittest discover -s unit_tests -v > test_reports/test_reports.txt 2>&1
          exit_code=$?
          echo "Exit code: $exit_code"
          exit $exit_code

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: test_reports/test_reports.txt